# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #!the base hostname & protocol for your site e.g. https://www.someone.com (!!required!!)
url:  http://hmchzb19.github.io
baseurl: / 
title: hmchzb19's blog
description: > #this means to ignore newlines until "nav_lists:"
  hmchzb19's Blog

nav_lists:
  # - title: About
  - titles:
      en: Linuxer
      zh: Linuxer
      zh-Hans: Linuxer
      zh-Hant: Linuxer
    url: /about.html


paths:
  home: /
  all:  /all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: hmchzb19/hmchzb19.github.io
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: hmchzb19
  # email:  #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  # github:  #your GitHub username
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html ## text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - README.md
  - LICENSE
  - /vendor
  - /docs
  - /screenshots
  - /test

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
